version: '3.8'

services:
  ai_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai_script_api
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb+srv://nguyenvanninh:MM1onTUoA1sF4AnZ@onebizai.tt3rs.mongodb.net/test?retryWrites=true&w=majority
      - DB_NAME=test
      - AI_VERSION=1.0.0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "7000:7000"
    volumes:
      - ./logs:/app/logs
      - nltk_data:/home/appuser/nltk_data  # Cache NLTK data
    networks:
      - ai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
volumes:
  nltk_data:

networks:
  ai_network:
    driver: bridge
